name: Build 

on:
    push:
      branches:
        - master
        - development
  
jobs:
    build-api:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive
  
        - uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Build API image
          run: docker build -t ${{ secrets.API_IMAGE }} --build-arg user=radian --build-arg uid=1000 -f ./deployment/dockerFile/Dockerfile .
  
        - name: Push API image
          run: docker push ${{ secrets.API_IMAGE }}
  